### ISSUE TITLE
Add "go-c8y-cli-extension" topic to about page

### ISSUE THREAD

**Issue by reubenmiller** [reubenmiller/c8y-oee#6]
To make go-c8y-cli extensions more discoverable, the following topic should be added to the repo (e.g. in the "About" configuration settings).

* go-c8y-cli-extension

<img width="556" alt="image" src="https://github.com/SoftwareAG/c8y-bpl/assets/3029781/0815db0a-85f7-4f14-aff0-4fbb2fb143f7">

**Comment by mvoigt-sag** [comment]
done.
